language: python
python:
    - 2.7
    - 3.4
notifications:
  email: false

services:
  - postgresql
addons:
  postgresql: "9.4"
before_install:
- sudo apt-get update
- sudo apt-get install libblas-dev liblapack-dev libatlas-base-dev gfortran
- sudo apt-get install libhdf5-serial-dev
install:
- pip install -r requirements.txt
script: py.test -vvv -s --cov=timechop
after_success: codecov
